@base_url=http://localhost:3000/api
###
{{base_url}}/users
###
GET {{base_url}}/users

###
POST {{base_url}}/users
Content-Type: application/json

{
    "last_name": "mouhamed",
    "first_name": "saadaoui",
    "email": "mmm.Goe@FHP.com",
    "password": "password123"
}

###
GET {{base_url}}/boxers/:id

###
GET {{base_url}}/boxers

###
POST {{base_url}}/boxers
Content-Type: application/json

{
        "first_name": "Khamzat",
        "last_name": "Chimaev",
        "email": "khamzat_chimaev@example.com",
        "height": "6'2\"",
        "weight": "170 lbs",
        "fight_number": "10",
        "win": "10",
        "losses": "0",
        "kos": "7",
        "gym_number": "5678",
        "title": "Welterweight Rising Star",
        "image_link": "https://example.com/khamzat_chimaev.jpg",
        "trainer_name": "Ali Abdelaziz"
    }

###
PUT {{base_url}}/boxers/1
Content-Type: application/json

{
    "first_name": "UpdatedName"
}

###
DELETE {{base_url}}/boxers/:id

###
POST {{base_url}}/auth/login
Content-Type: application/json

{
    "email": "mmm.Goe@FHP.com",
    "password": "password123"
}
###
POST {{base_url}}/auth/logout
Authorization: Bearer mmm.Goe@FHP.com-lqeyfrle


###
{{base_url}}/boxers/favorites
Authorization: Bearer mmm.Goe@FHP.com-lqe15fc7
